### ISSUE TITLE
How to install in my own instance ?

### ISSUE THREAD

**Issue by gamersalpha** [idrissneumann/mastodon-term-services#1]
Hello, 
how to install the Old Twiter theme on my mastodon instance please ?

**Comment by idrissneumann** [comment]
Either you pick the [custom.css](https://github.com/idrissneumann/mastodon-term-services/blob/main/custom.css) content and you cc/cl in the custom CSS texterea 

<img width="1158" alt="Screenshot 2023-11-02 at 16 50 39" src="https://github.com/idrissneumann/mastodon-term-services/assets/12884347/71ae673d-211c-4a36-932d-b8bf15bdc84a">

Or you if you want to manage like me in a gitops way, you can clone this repo and register gitlab ou github runner using the python scripts in your CICD.
